---
# This file is managed by the stacks toolchain. It may be overwritten by
# updates to the template. Your customizations should be placed inside the
# .kitchen.local.yml, which will not be overwritten by newer templates.
# If you need to override the driver, do it in ~/.kitchen/config.yml or using
# environment variables like VAGRANT_DEFAULT_PROVIDER.

driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 80, host: 8000, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4
  client_rb:
    environment: _default
  attributes:
    cloud:
      public_ipv4: '127.0.0.1'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      cloud_backup:
        enabled: false
      cloud_monitoring:
        enabled: false
      omnibus_updater:
        enabled: false
    rackspace:
      cloud_credentials:
        username: 'racker'
        api_key: 'sekrit'
    jenkinsstack:
      proxy_password: 'testingonly'

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.5
    run_list:
    - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[jenkinsstack::java]
      - recipe[jenkinsstack::master]
      - recipe[jenkinsstack::ruby]
      - recipe[jenkinsstack::find_all]
  - name: slave
    run_list:
      - recipe[jenkinsstack::java]
      - recipe[jenkinsstack::slave]
      - recipe[jenkinsstack::ruby]
      - recipe[jenkinsstack::find_all]
